// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPInfoClient is an autogenerated mock type for the IPInfoClient type
type IPInfoClient struct {
	mock.Mock
}

// GetInfo provides a mock function with given fields: ip
func (_m *IPInfoClient) GetInfo(ip string) (map[string]interface{}, error) {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(ip)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPInfoClient creates a new instance of IPInfoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPInfoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPInfoClient {
	mock := &IPInfoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
